plugins:
  - name: lint-plugin
    # For this to work, you must first `bazel build dev` in the root of the repo
    from: ../bazel-bin/plugin
    log_level: warn
    properties:
      lint_aspects:
        - //:lint.bzl%eslint
        - //:lint.bzl%buf
