lint:
  aspects:
    - //tools/lint:linters.bzl%eslint
    - //tools/lint:linters.bzl%buf
    - //tools/lint:linters.bzl%flake8
    - //tools/lint:linters.bzl%ktlint
    - //tools/lint:linters.bzl%pmd
    - //tools/lint:linters.bzl%stylelint
    - //tools/lint:linters.bzl%ruff
    - //tools/lint:linters.bzl%vale
    - //tools/lint:linters.bzl%checkstyle
    - //tools/lint:linters.bzl%clang_tidy
