# Tag a new release
# This is easier than having to run manual `git` operations on a local clone.
# It also runs on a schedule so we don't leave commits unreleased indefinitely
# (avoiding users having to ping "hey could someone cut a release").

on:
  # Allow devs to tag manually through the GitHub UI.
  # For example after landing a fix that customers are waiting for.
  workflow_dispatch:

  # Run every Monday at 3PM UTC (8AM PST)
  # NB: would prefer to trigger less frequently, perhaps bi-weekly, see
  # https://medium.com/@VeselyCodes/bi-weekly-github-actions-7bea6be7bd96
  schedule:
    - cron: "0 15 * * 1"

jobs:
  tag:
    permissions:
      # create tag
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.ccv.outputs.new-tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Need enough history to find the prior release tag
          fetch-depth: 0
      - name: Bump tag if necessary
        id: ccv
        uses: smlx/ccv@d3de774e9b607b079940a7a86952f44643743336 # v0.9.0
  release:
    needs: tag
    uses: ./.github/workflows/release.yml
    if: needs.tag.outputs.new-tag == 'true'
